// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgHR2J-EWBz8aLc6fVk5NvWNXd6_owmMo',
    appId: '1:211629639790:web:b3d925a507c3be909ffe7f',
    messagingSenderId: '211629639790',
    projectId: 'proyek-amankanjalan',
    authDomain: 'proyek-amankanjalan.firebaseapp.com',
    databaseURL: 'https://proyek-amankanjalan-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-amankanjalan.firebasestorage.app',
    measurementId: 'G-C1RS4BDHCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVbodiKRScuqPygQ679ug8VU91xRNMg9c',
    appId: '1:211629639790:android:417af69a4d13acaa9ffe7f',
    messagingSenderId: '211629639790',
    projectId: 'proyek-amankanjalan',
    databaseURL: 'https://proyek-amankanjalan-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-amankanjalan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTN_O640DSGMbg63QiIe0uWZmgGOl1tAk',
    appId: '1:211629639790:ios:c0a7ef3a854fd02e9ffe7f',
    messagingSenderId: '211629639790',
    projectId: 'proyek-amankanjalan',
    databaseURL: 'https://proyek-amankanjalan-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-amankanjalan.firebasestorage.app',
    iosBundleId: 'com.example.proyekAmankanjalan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTN_O640DSGMbg63QiIe0uWZmgGOl1tAk',
    appId: '1:211629639790:ios:c0a7ef3a854fd02e9ffe7f',
    messagingSenderId: '211629639790',
    projectId: 'proyek-amankanjalan',
    databaseURL: 'https://proyek-amankanjalan-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-amankanjalan.firebasestorage.app',
    iosBundleId: 'com.example.proyekAmankanjalan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgHR2J-EWBz8aLc6fVk5NvWNXd6_owmMo',
    appId: '1:211629639790:web:1125c1be8236cf349ffe7f',
    messagingSenderId: '211629639790',
    projectId: 'proyek-amankanjalan',
    authDomain: 'proyek-amankanjalan.firebaseapp.com',
    databaseURL: 'https://proyek-amankanjalan-default-rtdb.firebaseio.com',
    storageBucket: 'proyek-amankanjalan.firebasestorage.app',
    measurementId: 'G-X3S1BVHP0W',
  );
}
